stages:
    - prepare
    - build

prepare rust image:
    stage: prepare
    tags:
        - docker-available
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull "$(grep '^FROM' Dockerfile.build | awk '{ print $2; }' | head -n1)"
        - docker build -t "${CI_REGISTRY_IMAGE}:build" -f Dockerfile.build .
        - docker push "${CI_REGISTRY_IMAGE}:build"

build dynamic binary:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}:build"
    script:
        - cargo build --verbose
        - cargo build --release
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - target/release/dfwrs

build static library:
    stage: build
    tags:
        - rust-cross
    script:
        - cross build --target x86_64-unknown-linux-musl --release
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - target/x86_64-unknown-linux-musl/release/dfwrs

rustfmt:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}:build"
    script:
        - cargo fmt -- --write-mode diff
    allow_failure: true

