stages:
    - build

build:
    stage: build
    tags:
        - docker
    image: scorpil/rust:1.16
    script:
        - apt-get update
        - apt-get install -y --no-install-recommends libssl-dev make
        - cargo build --verbose
        - cargo build --release
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - target/release/dfwrs

