stages:
    - prepare
    - build
    - test
    - package

cache:
    key: "$CI_JOB_NAME"
    paths:
        - target/

.prepare-rust-image: &prepare-rust-image
    stage: prepare
    tags:
        - docker-available
        - local
    script:
        - JOB_NAME=( $CI_JOB_NAME )
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull "$(grep '^FROM' Dockerfile.build | awk '{ print $2; }' | head -n1)"
        - docker build -t "${CI_REGISTRY_IMAGE}/build:${JOB_NAME[3]}" -f Dockerfile.build .
        - docker push "${CI_REGISTRY_IMAGE}/build:${JOB_NAME[3]}"

prepare rust image stable: *prepare-rust-image
prepare rust image beta: *prepare-rust-image
prepare rust image nightly: *prepare-rust-image

rustfmt:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:stable"
    script:
        - cargo fmt -- --write-mode diff

build dynamic binary on stable:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:stable"
    script:
        - cargo build --verbose
    cache:
        key: "dynamic binary on stable"
        paths:
            - target/
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build dynamic binary on beta:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:beta"
    script:
        - cargo build --verbose
    cache:
        key: "dynamic binary on beta"
        paths:
            - target/
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build dynamic binary on nightly:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:nightly"
    script:
        - cargo build --verbose
    cache:
        key: "dynamic binary on nightly"
        paths:
            - target/
    allow_failure: true
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build static binary:
    stage: build
    tags:
        - rust-cross
        - local
    script:
        - cross build --target x86_64-unknown-linux-musl --release
        - cp target/x86_64-unknown-linux-musl/release/dfwrs dfwrs
    cache:
        key: "static binary"
        paths:
            - target/
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - dfwrs

test dynamic binary on stable:
    stage: test
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:stable"
    dependencies: []
    script:
        - cargo test -- --nocapture
    cache:
        key: "dynamic binary on stable"
        paths:
            - target/

test dynamic binary on beta:
    stage: test
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:beta"
    dependencies: []
    script:
        - cargo test -- --nocapture
    cache:
        key: "dynamic binary on beta"
        paths:
            - target/

test dynamic binary on nightly:
    stage: test
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:nightly"
    dependencies: []
    script:
        - cargo test -- --nocapture
    cache:
        key: "dynamic binary on nightly"
        paths:
            - target/
    allow_failure: true

test static binary:
    stage: test
    tags:
        - rust-cross
        - local
    dependencies: []
    script:
        - cross test --target x86_64-unknown-linux-musl -- --nocapture
    cache:
        key: "static binary"
        paths:
            - target/

.test-docker-tests: &test-docker-tests
    stage: test
    tags:
        - rust
        - docker-available
    dependencies: []
    before_script:
        # Extract docker version
        - JOB_NAME=( $CI_JOB_NAME )
        - echo "$JOB_NAME"
        - DIND_VERSION="${JOB_NAME[3]}"
        - echo "$DIND_VERSION"
        # Start dind-container
        - >
            docker run
            --rm -d --name "dind-runner-${CI_JOB_ID}" --privileged
            "docker:$DIND_VERSION-dind" --iptables=false
        # Get dind-container IP
        - DIND_IP_ADDRESS="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "dind-runner-${CI_JOB_ID}")"
        - echo "$DIND_IP_ADDRESS"
        # Wait for dind-container to be ready
        - >
            until docker -H "tcp://${DIND_IP_ADDRESS}:2375" info >/dev/null 2>&1; do sleep 1; done
        - export DOCKER_HOST="http://${DIND_IP_ADDRESS}:2375"
        - echo "$DOCKER_HOST"
    script:
        - RUST_TEST_THREADS=1 cargo test --all-features -j1 -- --nocapture
    after_script:
        - docker stop "dind-runner-${CI_JOB_ID}"

# API from 1.12.6 and below is not compatible.
test on docker 1.13.0: *test-docker-tests
test on docker 1.13.1: *test-docker-tests
test on docker 17.03.0-ce: *test-docker-tests
test on docker 17.03.1-ce: *test-docker-tests
test on docker 17.04.0-ce: *test-docker-tests
test on docker 17.05.0-ce: *test-docker-tests

package image for feature-branch:
    stage: package
    tags:
        - docker-available
        - local
    dependencies:
        - build static binary
    only:
        - branches
    except:
        - master
        - /^develop\/.*$/
    script:
        - docker build -t "${CI_REGISTRY_IMAGE}/branches:${CI_COMMIT_REF_SLUG}" .
        - docker image rm "${CI_REGISTRY_IMAGE}/branches:${CI_COMMIT_REF_SLUG}"

package and push image for tags:
    stage: package
    tags:
        - docker-available
        - local
    dependencies:
        - build static binary
    only:
        - tags
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" .
        - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

package and push image on develop patch:
    stage: package
    tags:
        - docker-available
        - local
    dependencies:
        - build static binary
    only:
        - develop/patch
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t "${CI_REGISTRY_IMAGE}/develop:patch" .
        - docker push "${CI_REGISTRY_IMAGE}/develop:patch"

package and push image on develop minor:
    stage: package
    tags:
        - docker-available
        - local
    dependencies:
        - build static binary
    only:
        - develop/minor
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t "${CI_REGISTRY_IMAGE}/develop:minor" .
        - docker push "${CI_REGISTRY_IMAGE}/develop:minor"

package and push image on master:
    stage: package
    tags:
        - docker-available
        - local
    dependencies:
        - build static binary
    only:
        - master
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE

