stages:
    - prepare
    - build
    - package

cache:
    key: "$CI_JOB_NAME"
    paths:
        - target/

prepare rust image:
    stage: prepare
    tags:
        - docker-available
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull "$(grep '^FROM' Dockerfile.build | awk '{ print $2; }' | head -n1)"
        - docker build -t "${CI_REGISTRY_IMAGE}/build" -f Dockerfile.build .
        - docker push "${CI_REGISTRY_IMAGE}/build"

build dynamic binary:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build"
    script:
        - cargo build --verbose
        - cargo build --release
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - target/release/dfwrs

build static binary:
    stage: build
    tags:
        - rust-cross
    script:
        - cross build --target x86_64-unknown-linux-musl --release
        - cp target/x86_64-unknown-linux-musl/release/dfwrs dfwrs
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - dfwrs

rustfmt:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build"
    script:
        - cargo fmt -- --write-mode diff
    allow_failure: true

package image for feature-branch:
    stage: package
    tags:
        - docker-available
    dependencies:
        - build static binary
    only:
        - branches
    except:
        - master
        - /^develop\/.*$/
    script:
        - docker build -t "${CI_REGISTRY_IMAGE}/branches:${CI_COMMIT_REF_SLUG}" .
        - docker image rm "${CI_REGISTRY_IMAGE}/branches:${CI_COMMIT_REF_SLUG}"

package and push image for tags:
    stage: package
    tags:
        - docker-available
    dependencies:
        - build static binary
    only:
        - tags
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" .
        - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

package and push image on develop patch:
    stage: package
    tags:
        - docker-available
    dependencies:
        - build static binary
    only:
        - develop/patch
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t "${CI_REGISTRY_IMAGE}/develop:patch" .
        - docker push "${CI_REGISTRY_IMAGE}/develop:patch"

package and push image on develop minor:
    stage: package
    tags:
        - docker-available
    dependencies:
        - build static binary
    only:
        - develop/minor
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t "${CI_REGISTRY_IMAGE}/develop:minor" .
        - docker push "${CI_REGISTRY_IMAGE}/develop:minor"

package and push image on master:
    stage: package
    tags:
        - docker-available
    dependencies:
        - build static binary
    only:
        - master
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE

