[package]
name = "dfw"
version = "0.4.1-alpha.0"
authors = ["Pit Kleyersburg <pitkley@googlemail.com>"]
license = "MIT/Apache-2.0"
description = "Docker firewall framework, in Rust"
homepage = "https://github.com/pitkley/dfw"
repository = "https://github.com/pitkley/dfw.git"

categories = ["command-line-interface", "command-line-utilities"]
keywords = ["cli", "docker", "firewall"]

include = [
    "**/*.rs",
    "resources/**/*",
    "Cargo.toml",
    "LICENSE-*",
]

[dependencies]
chan = "^0.1"
chan-signal = "^0.3"
clap = "^2.31"
derive_builder = "^0.5"
failure= "^0.1"
glob = "^0.2"
iptables = "^0.2"
libc = "^0.2"
serde = "^1"
serde_derive = "^1"
shiplift = "^0.3"
slog = "^2"
slog-async = "^2"
slog-term = "^2"
time = "^0.1"
toml = "^0.4"
url = "^1.7"

[dev-dependencies]
eval = "^0.4"
lazy_static = "^1"
maplit = "^1"
regex = "^1"

[[bin]]
name = "dfw"
path = "src/bin/dfw.rs"
doc = false

[features]
docker-tests = []
iptables-tests = []

[profile.release]
lto = true
codegen-units = 1
incremental = false

