[package]
name = "dfwrs"
version = "0.0.1"
authors = ["Pit Kleyersburg <pitkley@googlemail.com>"]

[dependencies]
boondock = { git = "https://github.com/pitkley/boondock", branch = "extend-api" }
derive_builder = "^0.4.2"
error-chain = "^0.10.0"
serde = "^0.9.13"
serde_derive = "^0.9.13"
toml = "^0.3.2"

