[package]
name = "dfwrs"
version = "0.1.2"
authors = ["Pit Kleyersburg <pitkley@googlemail.com>"]

[dependencies]
chan = "~0.1.19"
chan-signal = "~0.2.0"
clap = "~2.23.3"
derive_builder = "~0.4.2"
error-chain = "~0.10.0"
glob = "~0.2.11"
iptables = { git = "https://github.com/pitkley/rust-iptables", branch = "extend-api" }
serde = "~0.9.13"
serde_derive = "~0.9.13"
shiplift = { git = "https://github.com/softprops/shiplift", rev = "1e248234625c85c0716eb3924b386efae12356f6" }
toml = "~0.3.2"
url = "~1.4.0"

[package.metadata.release]
sign-commit = true
upload-doc = false

