[package]
name = "dfwrs"
version = "0.2.0-pre"
authors = ["Pit Kleyersburg <pitkley@googlemail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
chan = "~0.1.19"
chan-signal = "~0.2.0"
clap = "~2.23.3"
derive_builder = "~0.4.2"
error-chain = "~0.10.0"
glob = "~0.2.11"
iptables = "~0.2.0"
libc = "~0.2.21"
serde = "~1.0.1"
serde_derive = "~1.0.1"
shiplift = { git = "https://github.com/softprops/shiplift", rev = "1e248234625c85c0716eb3924b386efae12356f6" }
slog = "~2.0.2"
slog-async = "~2.0.1"
slog-term = "~2.0.0-4.0"
time = "~0.1.37"
toml = "~0.4.0"
url = "~1.4.0"

[package.metadata.release]
sign-commit = true
upload-doc = false

