external_network_interface = "ens3"

[initialization]
filter = [
    "-P INPUT DROP",
    "-F INPUT",
]

[container_to_container]
default_policy = "DROP"

[[container_to_container.rules]]
network = "some_network"
src_container = "srccnt"
dst_container = "dstcnt"
filter = "-p tcp --dport 25"
action = "ACCEPT"

[[container_to_container.rules]]
network = "some_network"
# OPTIONAL src_container = "srccnt"
# OPTIONAL dst_container = "dstcnt"
# OPTIONAL filter = "-p tcp --dport 25"
action = "ACCEPT"

[container_to_wider_world]
default_policy = "ACCEPT"

[[container_to_wider_world.rules]]
network = "jenkins_default"
src_container = "hi"
filter = "-p tcp"
action = "ACCEPT"
external_network_interface = ["ens3"]

[[container_to_wider_world.rules]]
# OPTIONAL network = "jenkins_default"
# OPTIONAL src_container = "hi"
# OPTIONAL filter = "-p tcp"
action = "ACCEPT"
# OPTIONAL external_network_interface = ["ens3"]

[container_to_host]
default_policy = "ACCEPT"

[[container_to_host.rules]]
network = "some"
src_container = "cont"
filter = "filter"
action = "OTHER"

[[container_to_host.rules]]
network = "some"
# OPTIONAL src_container = "cont"
# OPTIONAL filter = "filter"
action = "OTHER"

[wider_world_to_container]

[[wider_world_to_container.rules]]
network = "network"
dst_container = "dst_container"
expose_port = 1
external_network_interface = ["someif"]

[[wider_world_to_container.rules]]
network = "network"
dst_container = "dst_container"
expose_port = "2"
external_network_interface = ["someif"]

[[wider_world_to_container.rules]]
network = "network"
dst_container = "dst_container"
expose_port = "3/tcp"
# OPTIONAL external_network_interface = ["someif"]

[[wider_world_to_container.rules]]
network = "network"
dst_container = "dst_container"
expose_port = { host_port = 4, container_port = 101, family = "tcp" }

[[wider_world_to_container.rules]]
network = "network"
dst_container = "dst_container"
expose_port = { host_port = 5, family = "tcp" }

[[wider_world_to_container.rules]]
network = "network"
dst_container = "dst_container"
expose_port = { host_port = 6, container_port = 102 }
