[defaults]
external_network_interface = "ens3"

[initialization.v4]
filter = [
    "-P INPUT ACCEPT",
    "-F INPUT",
    "-A INPUT -i docker0 -j ACCEPT",
]

[initialization.v6]
filter = [
    "-P INPUT ACCEPT",
    "-F INPUT",
    "-A INPUT -i docker0 -j ACCEPT",
]

[container_to_container]
default_policy = "DROP"

[[container_to_container.rules]]
network = "dfwrs_proxy"
src_container = "dfwrs_proxy_1"
action = "ACCEPT"

[[container_to_container.rules]]
network = "dfwrs_a"
src_container = "dfwrs_a_1"
dst_container = "dfwrs_b_1"
action = "ACCEPT"

[[container_to_container.rules]]
network = "dfwrs_b"
action = "ACCEPT"

[container_to_wider_world]
default_policy = "ACCEPT"

[[container_to_wider_world.rules]]
network = "dfwrs_proxy"
filter = "-p tcp"
action = "ACCEPT"
external_network_interface = "ens3"

[[container_to_wider_world.rules]]
network = "dfwrs_b"
action = "ACCEPT"
external_network_interface = "lxdbr0"

[container_to_host]
default_policy = "ACCEPT"

[[container_to_host.rules]]
network = "dfwrs_a"
action = "ACCEPT"

[[container_to_host.rules]]
network = "dfwrs_b"
src_container = "dfwrs_b_1"
action = "DROP"

[wider_world_to_container]

[[wider_world_to_container.rules]]
network = "dfwrs_proxy"
dst_container = "dfwrs_proxy_1"
expose_port = 80

[[wider_world_to_container.rules]]
network = "dfwrs_proxy"
dst_container = "dfwrs_proxy_1"
expose_port = { host_port = 443 }

[[wider_world_to_container.rules]]
network = "dfwrs_a"
dst_container = "dfwrs_a_1"
expose_port = { host_port = 8080, container_port = 80, family = "tcp" }
external_network_interface = "lxdbr0"

[[wider_world_to_container.rules]]
network = "dfwrs_b"
dst_container = "dfwrs_b_1"
expose_port = { host_port = 8081, container_port = 80, family = "udp" }

[container_dnat]

[[container_dnat.rules]]
src_network = "dfwrs_a"
src_container = "dfwrs_a_1"
dst_network = "dfwrs_b"
dst_container = "dfwrs_b_1"
expose_port = { host_port = 80, family = "tcp" }

[[container_dnat.rules]]
dst_network = "dfwrs_a"
dst_container = "dfwrs_a_1"
expose_port = "53/udp"

